version: '3.8'

services:
  app:
    container_name: app
    build: ./app
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - ${APP_PORT}:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL
    stdin_open: true

  api:
    container_name: api
    build: ./api
    volumes:
      - './api:/api'
    ports:
      - ${API_PORT}:5000
    environment:
      - API_PORT
      - ENVIRONMENT=development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
